[package]
name = "smrpg-readwrite"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.9"

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 1
